#!/bin/bash





#DO NOT EDIT THIS FILE
#======================================================

if lsof -i :419 | grep LISTEN; then
    echo "Port 419 is already in use. Stopping existing process..."
    sudo kill -9 $(lsof -t -i :419)
    sleep 2
fi

php -S localhost:419 > php_server.log 2>&1 &
echo "\e[32m✅Server running on http://localhost:419\e[0m"

# Wait for the server to start
sleep 2

if command -v cloudflared &> /dev/null
then
    echo "✅Starting Cloudflared..."
    
    cloudflared tunnel --url http://localhost:419 | tee cloudflared.log &

    sleep 5

    CLOUDFLARED_URL=$(grep -o 'https://[^ ]*\.trycloudflare.com' cloudflared.log | head -n 1)

    if [[ -n "$CLOUDFLARED_URL" ]]
    then
        echo "\e[32m✅Cloudflared started successfully!\e[0m"
        echo "\e[32m✅Your public link: $CLOUDFLARED_URL \e[0m"
    else
        echo "\e[31m⚠️Cloudflared failed to start or no public URL found. Check cloudflared.log for details.\e[0m"
    fi
else
    echo "\e[31m❌Cloudflared is not installed. Running only on localhost.\e[0m"
fi
