#!/bin/bash

# DO NOT EDIT THIS FILE
#======================================================
if [ -z "$FROM_START" ]; then
    echo -e "\e[31m❌ You cannot run server.sh directly! Please use start.sh\e[0m"
    exit 1
fi


# Check if Port 419 is already in use and stop it
if lsof -i :419 | grep LISTEN; then
    echo "Port 419 is already in use. Stopping existing process..."
    sudo kill -9 $(lsof -t -i :419)
    sleep 2
fi

# Start PHP built-in server
php -S localhost:419 > php_server.log 2>&1 &
echo -e "\e[32m✅ Server running on http://localhost:419\e[0m"
echo -e "\n"

# Wait for the server to start
sleep 2

# Check if Cloudflared is installed
if command -v cloudflared &> /dev/null; then
    echo "✅ Starting Cloudflared..."
    echo -e "\n"
    # Start Cloudflared as a standalone process and capture output
    cloudflared tunnel --url http://localhost:419 | tee cloudflared.log &

    # Wait a few seconds for Cloudflared to establish the tunnel
    sleep 5

    # Extract the public URL
    CLOUDFLARED_URL=$(grep -o 'https://[^ ]*\.trycloudflare.com' cloudflared.log | head -n 1)

    if [[ -n "$CLOUDFLARED_URL" ]]; then
        echo -e "\e[32m✅ Cloudflared started successfully!\e[0m"
        echo -e "\n"
        echo -e "\e[32m✅ Your public link: $CLOUDFLARED_URL\e[0m"
    else
        echo -e "\e[31m⚠️ Cloudflared failed to start or no public URL found. Check cloudflared.log for details.\e[0m"
    fi
else
    echo -e "\e[31m❌ Cloudflared is not installed. Running only on localhost.\e[0m"
fi
